/**
 * WeChat run-all bot: send `/run` from another WeChat account and this example
 * replies with every outbound content path the provider currently supports.
 *
 * Run it against a live agent-wechat container:
 *
 *   pnpm build
 *   AGENT_WECHAT_TOKEN=$(cat ~/.config/agent-wechat/token) pnpm example:run-all
 *
 * Notes:
 * - MP4 files are handled by WeChat as native video messages.
 * - Native WeChat voice bubbles are not exposed by agent-wechat today; voice
 *   is delivered as an audio file.
 * - Group chats use `groups: "mentionsOnly"` by default, so mention the bot
 *   and include `/run` in the same message.
 */
import { deflateSync } from "node:zlib";
import { Spectrum, app, attachment, contact, markdown, richlink, voice } from "@spectrum-ts/core";
import type { ContentInput, Message, Space } from "@spectrum-ts/core";
import { wechat } from "photon-wechat-sdk";

const RUN_COMMAND = "/run";

const delay = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

const activeRuns = new Set<string>();

const appInstance = await Spectrum({
  providers: [
    wechat.config({
      baseUrl: process.env.AGENT_WECHAT_URL ?? "http://localhost:6174",
      token: process.env.AGENT_WECHAT_TOKEN,
      pollIntervalMs: 1500,
      sendPacingMs: 1000,
      groups: groupPolicyFromEnv(),
    }),
  ],
});

console.error("[run-all] listening for /run messages... (Ctrl-C to stop)");

for await (const [space, message] of appInstance.messages) {
  const text = message.content.type === "text" ? message.content.text.trim() : "";
  if (!text.includes(RUN_COMMAND)) continue;

  if (activeRuns.has(space.id)) {
    await space.send("run-all is already running for this chat.");
    continue;
  }

  activeRuns.add(space.id);
  try {
    await runAll(space, message);
  } finally {
    activeRuns.delete(space.id);
  }
}

async function runAll(space: Space, trigger: Message): Promise<void> {
  const runId = new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14);
  const results: string[] = [];

  await space.startTyping();
  await delay(400);
  await space.stopTyping();
  await trigger.read();

  await space.send(`run-all ${runId}: starting outbound content sweep.`);

  const steps: Array<{ name: string; send: () => Promise<void> }> = [
    {
      name: "reply",
      send: async () => {
        await trigger.reply(`run-all ${runId}: reply sample to your /run message.`);
      },
    },
    {
      name: "text",
      send: async () => {
        await space.send(`run-all ${runId}: plain text sample.`);
      },
    },
    {
      name: "markdown",
      send: async () => {
        await space.send(markdown(`**run-all ${runId}** markdown sample\n\n- item one\n- item two`));
      },
    },
    {
      name: "richlink",
      send: async () => {
        await space.send(richlink("https://photon.codes/spectrum"));
      },
    },
    {
      name: "app-url",
      send: async () => {
        await space.send(app("https://photon.codes/spectrum"));
      },
    },
    {
      name: "image",
      send: async () => {
        await space.send(bufferAttachment("run-all-image.png", "image/png", makePng()));
      },
    },
    {
      name: "video",
      send: async () => {
        await space.send(bufferAttachment("run-all-video.mp4", "video/mp4", makeMp4()));
      },
    },
    {
      name: "voice-file",
      send: async () => {
        await space.send(
          voice(makeWav({ durationSeconds: 1.2, frequencyHz: 440 }), {
            duration: 1.2,
            mimeType: "audio/wav",
            name: "run-all-voice.wav",
          }),
        );
      },
    },
    {
      name: "generic-file",
      send: async () => {
        await space.send(
          bufferAttachment(
            "run-all-file.json",
            "application/json",
            Buffer.from(
              JSON.stringify(
                {
                  runId,
                  generatedBy: "examples/run-all-bot.ts",
                  purpose: "photon-wechat-sdk outbound file smoke test",
                },
                null,
                2,
              ),
              "utf8",
            ),
          ),
        );
      },
    },
    {
      name: "contact-vcard",
      send: async () => {
        await space.send(
          contact({
            name: { formatted: "Photon WeChat Run All" },
            emails: [{ value: "run-all@example.invalid", type: "work" }],
            org: {
              name: "photon-wechat-sdk",
              title: "Synthetic test contact",
            },
            urls: ["https://photon.codes/spectrum"],
            note: `Generated by examples/run-all-bot.ts for ${runId}.`,
          }),
        );
      },
    },
  ];

  for (const step of steps) {
    try {
      console.error(`[run-all] ${runId} sending ${step.name} to ${space.id}`);
      await step.send();
      results.push(`${step.name}=ok`);
    } catch (error) {
      const message = errorMessage(error);
      console.error(`[run-all] ${runId} ${step.name} failed: ${message}`);
      results.push(`${step.name}=fail`);
      await space.send(`run-all ${runId}: ${step.name} failed: ${message}`);
    }
  }

  await space.send(
    [
      `run-all ${runId}: complete.`,
      `Results: ${results.join(", ")}`,
      "Native WeChat voice bubbles, reactions, polls, edit, unsend, rename, and avatar are not currently supported by this provider.",
    ].join("\n"),
  );
}

function bufferAttachment(name: string, mimeType: string, bytes: Buffer): ContentInput {
  return attachment(bytes, { mimeType, name });
}

function groupPolicyFromEnv(): "exclude" | "include" | "mentionsOnly" {
  const value = process.env.WECHAT_GROUPS;
  if (value === "exclude" || value === "include" || value === "mentionsOnly") {
    return value;
  }
  return "mentionsOnly";
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function makePng(): Buffer {
  const width = 64;
  const height = 64;
  const rows: Buffer[] = [];

  for (let y = 0; y < height; y += 1) {
    const row = Buffer.alloc(1 + width * 3);
    row[0] = 0;
    for (let x = 0; x < width; x += 1) {
      const offset = 1 + x * 3;
      row[offset] = (30 + x * 3) % 256;
      row[offset + 1] = (80 + y * 2) % 256;
      row[offset + 2] = (220 - x + y) % 256;
    }
    rows.push(row);
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 2;
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", deflateSync(Buffer.concat(rows))),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

function makeMp4(): Buffer {
  return Buffer.from(
    [
      "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAOybW9vdgAAAGxtdmhkAAAAAAAAAAAA",
      "AAAAAAAD6AAAA+gAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA",
      "AABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAtx0cmFrAAAAXHRraGQAAAADAAAA",
      "AAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAA",
      "AAAAAAAAAABAAAAAAEAAAABAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAAAIAAABAAAA",
      "AAJUbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAoAAAAKABVxAAAAAAALWhkbHIAAAAAAAAAAHZp",
      "ZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAB/21pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAA",
      "ACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAb9zdGJsAAAAv3N0c2QAAAAAAAAA",
      "AQAAAK9hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAEAAQABIAAAASAAAAAAAAAABAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAANWF2Y0MBZAAK/+EAGGdkAAqs2UQmwEQA",
      "AAMABAAAAwBQPEiWWAEABmjr48siwP34+AAAAAAQcGFzcAAAAAEAAAABAAAAFGJ0cnQAAAAAAAA6",
      "YAAAOmAAAAAYc3R0cwAAAAAAAAABAAAACgAABAAAAAAUc3RzcwAAAAAAAAABAAAAAQAAAGBjdHRz",
      "AAAAAAAAAAoAAAABAAAIAAAAAAEAABQAAAAAAQAACAAAAAABAAAAAAAAAAEAAAQAAAAAAQAAFAAA",
      "AAABAAAIAAAAAAEAAAAAAAAAAQAABAAAAAABAAAIAAAAABxzdHNjAAAAAAAAAAEAAAABAAAACgAA",
      "AAEAAAA8c3RzegAAAAAAAAAAAAAACgAABeUAAAB1AAAAGAAAAA0AAAANAAAAaQAAABwAAAAMAAAA",
      "DAAAACMAAAAUc3RjbwAAAAAAAAABAAAD4gAAAGJ1ZHRhAAAAWm1ldGEAAAAAAAAAIWhkbHIAAAAA",
      "AAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZm",
      "NTguNzYuMTAwAAAACGZyZWUAAAdUbWRhdAAAAq4GBf//qtxF6b3m2Ui3lizYINkj7u94MjY0IC0g",
      "Y29yZSAxNjMgcjMwNjAgNWRiNmFhNiAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVm",
      "dCAyMDAzLTIwMjEgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRpb25z",
      "OiBjYWJhYz0xIHJlZj0zIGRlYmxvY2s9MTowOjAgYW5hbHlzZT0weDM6MHgxMTMgbWU9aGV4IHN1",
      "Ym1lPTcgcHN5PTEgcHN5X3JkPTEuMDA6MC4wMCBtaXhlZF9yZWY9MSBtZV9yYW5nZT0xNiBjaHJv",
      "bWFfbWU9MSB0cmVsbGlzPTEgOHg4ZGN0PTEgY3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tp",
      "cD0xIGNocm9tYV9xcF9vZmZzZXQ9LTIgdGhyZWFkcz0yIGxvb2thaGVhZF90aHJlYWRzPTEgc2xp",
      "Y2VkX3RocmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9",
      "MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJmcmFtZXM9MyBiX3B5cmFtaWQ9MiBiX2FkYXB0PTEgYl9i",
      "aWFzPTAgZGlyZWN0PTEgd2VpZ2h0Yj0xIG9wZW5fZ29wPTAgd2VpZ2h0cD0yIGtleWludD0yNTAg",
      "a2V5aW50X21pbj0xMCBzY2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQw",
      "IHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBz",
      "dGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAAy9liIQAn+1zw0px/gtZ2P4Cj4J3NyQ1",
      "2+nO9F1hxS4IovTA89XOIAevd5TA69oZpNSQXmp43qUsLx5J7HnYA15qJoUZOAHjrdOk0CzZt50K",
      "KvoHNbILnjz+bDSbxP8RuUTJAm9s16HdU1iEOtR6X8WElFYgH8y41EVQyiatuYcf+fkzB5slptz0",
      "lNcGeMQQaZHPZ72cThDpzLztksP/75GbNl0rZvMlnY+Uvk019iwTeiI25PxbqftxL7OBk4jng5pd",
      "3fsA2q6QQO50OTaEznUsjXuEsMwAYN0T3yg4Tq+MexflpWmtDbddieUhwd3xvxfiM60jOqzOsYpO",
      "ZX4vWyhKwTBEezh0XDWu7aemEhAsL1rm0JE1B2Z4WrGt5l2AaVebTQGsJV1dCCOqT8RZIE1wFaGO",
      "z3LMrG2fWJZSxGf05/wM4GDh9YIOXEkpURifFzc2BXQyYPmpJdAH9ro9Auw4zPu+A1Gwbn/jAAwl",
      "B2N6iRfaRQa0d5dV/AHCPJ3C3aVoXh0J773rhwT+gYwBYYDV3XOEW01/+Qx2OloM62sqzIWFJlBV",
      "TFwKutX4pYN9Eht7W1+u+DR94VXrczS128qvlbmjfnNY96BY0d+KTNLiCnR4dneqhzcX+M9j+bvW",
      "NvCdCeA8IIXWTvCdAPQwfHLkYeA3JCZchexHFvLoRTb3fWOC38qi067187u5m3iNrvdmrwl9bEZY",
      "L9I6CF50TLoaRIdoexF6JM/3kqA0aTKySjUU+QkZLqllMcKTwUezDfp7WY0r1M5bTA68uzI5FeE+",
      "pgp/uooZoyt/p4b2M/1ca0slN6JLhdR/I/ySuJx+dNDDfnp0q9HzOgZLy/LFpfbKKVjQBmEh96wv",
      "Pgw6d0B1N/QhQAovhoX3kMnDSZlmguoaDcydp2o4hgqxFHrRPzXwenLywzdpRR636cIF4qZ5bn3H",
      "NqEzcXfwViOoVKf7SVR4OgrjgTRO6S2jY8Ikd4BaW4pmjsxb5Ia3vDho8LESQPj3QAUXkmwceqj5",
      "iFUARzHy+neTqIJCmX8bATJXMvl0crY9BVOPMZ2wop9v7O2dP6Yyz90NM5+N75KnC8RP9QAAAHFB",
      "miRsTf8OA3HMMvxhBLJqZFnQXuxdm0uN/pbyZXcc5Qfbyp2k8RysKF6ra1i7MQ7NUnGHz1xW/YJG",
      "2EfNt/yet9/72cik3K3MkiDV7zRdRT17an4O7m698m01kGyaRCyiuEmFS4uk8cu9O5GQ+IxcrwAA",
      "ABRBnkJ4jv+Cs/O5Y79vbPP39SlT2QAAAAkBnmF0Ql+RJ7sAAAAJAZ5jakJfd8i9AAAAZUGaaEmo",
      "QWiZTAjvDitWNL5LzDBjJ7fc/nddoz7mmychydH8TkXtE3gHo+uDRlIeywBHSNcWHcs7xSb+cyCW",
      "hJJ5FkrZkBjcO8Kmypnru05MX7SNQUywvvaJ5zycvRAB7J2hSWeBAAAAGEGehkURLHdjZ8wmh0HE",
      "TScCXpeXkJNzQQAAAAgBnqV0Ql9gwQAAAAgBnqdqQl9gwAAAAB9BmqlJqEFsmUwIS/8XQV/Mhaq5",
      "ZDUzgbbL8RBcfr+A",
    ].join(""),
    "base64",
  );
}

function makeWav(options: {
  durationSeconds: number;
  frequencyHz: number;
  sampleRate?: number;
}): Buffer {
  const sampleRate = options.sampleRate ?? 16_000;
  const sampleCount = Math.floor(options.durationSeconds * sampleRate);
  const dataSize = sampleCount * 2;
  const buffer = Buffer.alloc(44 + dataSize);

  buffer.write("RIFF", 0, "ascii");
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write("WAVE", 8, "ascii");
  buffer.write("fmt ", 12, "ascii");
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(1, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(sampleRate * 2, 28);
  buffer.writeUInt16LE(2, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write("data", 36, "ascii");
  buffer.writeUInt32LE(dataSize, 40);

  for (let i = 0; i < sampleCount; i += 1) {
    const t = i / sampleRate;
    const fadeIn = Math.min(1, i / (sampleRate * 0.03));
    const fadeOut = Math.min(1, (sampleCount - i) / (sampleRate * 0.05));
    const envelope = Math.min(fadeIn, fadeOut);
    const sample = Math.sin(2 * Math.PI * options.frequencyHz * t) * 0.35 * envelope;
    buffer.writeInt16LE(Math.round(sample * 32767), 44 + i * 2);
  }

  return buffer;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const typeBytes = Buffer.from(type, "ascii");
  return Buffer.concat([
    uint32BE(data.length),
    typeBytes,
    data,
    uint32BE(crc32(Buffer.concat([typeBytes, data]))),
  ]);
}

function crc32(data: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of data) {
    crc ^= byte;
    for (let i = 0; i < 8; i += 1) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function uint32BE(value: number): Buffer {
  const buffer = Buffer.alloc(4);
  buffer.writeUInt32BE(value, 0);
  return buffer;
}
